version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: npm install
      - run: npm run build

  deploy:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: npm install -g vercel
      - run: vercel --token $VERCEL_TOKEN --prod

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - main
